name: Deploy to OCI with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

    - name: Deploy to OCI
      env:
        OCI_SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
        OCI_HOST: ${{ secrets.OCI_HOST }}
        OCI_USER: ${{ secrets.OCI_USER }}
      run: |
        echo "$OCI_SSH_PRIVATE_KEY" > oci_key
        chmod 600 oci_key
        mkdir -p ~/.ssh
        ssh-keyscan -H $OCI_HOST >> ~/.ssh/known_hosts
        ssh -i oci_key $OCI_USER@$OCI_HOST "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest && docker stop react-app || true && docker rm react-app || true && docker run -d --name react-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest"